name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain with caching
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - name: Check
        run: RUSTFLAGS="--deny warnings" cargo check

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy

      - name: Audit
        run: cargo audit

      - name: Build (using cargo)
        run: RUSTFLAGS="--deny warnings" cargo build --profile release
